# Exercise 1.01
## Loading the dataset and creating the target

The goal of this exercise is to:
- Obtain the csv dataset from the UCI machine learning repository
- Load the dataset into memory as a pandas dataframe
- Identify an appropriate target to predict, and create a binary numerical column of the target

#### Download the dataset
Visit https://archive.ics.uci.edu/ml/datasets/Online+Shoppers+Purchasing+Intention+Dataset and download the files named `online_shoppers_intention.csv`. Create a folder named `data` and deposit the file in this folder.

The data is located in the `online_shoppers_intention.csv` file and information about the data is provided online at the UCI website here: https://archive.ics.uci.edu/ml/datasets/Online+Shoppers+Purchasing+Intention+Dataset.

Let's take a sneak peak of the data

In [6]:
!head ../data/online_shoppers_intention.csv

Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0,0,1,0,0.2,0.2,0,0,Feb,1,1,1,1,Returning_Visitor,FALSE,FALSE
0,0,0,0,2,64,0,0.1,0,0,Feb,2,2,1,2,Returning_Visitor,FALSE,FALSE
0,0,0,0,1,0,0.2,0.2,0,0,Feb,4,1,9,3,Returning_Visitor,FALSE,FALSE
0,0,0,0,2,2.666666667,0.05,0.14,0,0,Feb,3,2,2,4,Returning_Visitor,FALSE,FALSE
0,0,0,0,10,627.5,0.02,0.05,0,0,Feb,3,3,1,4,Returning_Visitor,TRUE,FALSE
0,0,0,0,19,154.2166667,0.015789474,0.024561404,0,0,Feb,2,2,1,3,Returning_Visitor,FALSE,FALSE
0,0,0,0,1,0,0.2,0.2,0,0.4,Feb,2,4,3,3,Returning_Visitor,FALSE,FALSE
1,0,0,0,0,0,0.2,0.2,0,0,Feb,1,2,1,5,Returning_Visitor,TRUE,FALSE
0,0,0,0,2,37,0,0.1,0,0.8,Feb,2,2,2,3,Returning_Visitor,FALSE,FALSE

Here we can see the first 10 rows of the data. We note that the column names are included.

In [7]:
import pandas as pd
data = pd.read_csv('../data/online_shoppers_intention.csv')

In [8]:
data.head(n=20)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
5,0,0.0,0,0.0,19,154.216667,0.015789,0.024561,0.0,0.0,Feb,2,2,1,3,Returning_Visitor,False,False
6,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.4,Feb,2,4,3,3,Returning_Visitor,False,False
7,1,0.0,0,0.0,0,0.000000,0.200000,0.200000,0.0,0.0,Feb,1,2,1,5,Returning_Visitor,True,False
8,0,0.0,0,0.0,2,37.000000,0.000000,0.100000,0.0,0.8,Feb,2,2,2,3,Returning_Visitor,False,False
9,0,0.0,0,0.0,3,738.000000,0.000000,0.022222,0.0,0.4,Feb,2,4,1,2,Returning_Visitor,False,False
10,0,0.0,0,0.0,3,395.000000,0.000000,0.066667,0.0,0.0,Feb,1,1,3,3,Returning_Visitor,False,False
11,0,0.0,0,0.0,16,407.750000,0.018750,0.025833,0.0,0.4,Feb,1,1,4,3,Returning_Visitor,False,False
12,0,0.0,0,0.0,7,280.500000,0.000000,0.028571,0.0,0.0,Feb,1,1,1,3,Returning_Visitor,False,False
13,0,0.0,0,0.0,6,98.000000,0.000000,0.066667,0.0,0.0,Feb,2,5,1,3,Returning_Visitor,False,False
14,0,0.0,0,0.0,2,68.000000,0.000000,0.100000,0.0,0.0,Feb,3,2,3,3,Returning_Visitor,False,False
15,2,53.0,0,0.0,23,1668.285119,0.008333,0.016313,0.0,0.0,Feb,1,1,9,3,Returning_Visitor,False,False
16,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Feb,1,1,4,3,Returning_Visitor,False,False
17,0,0.0,0,0.0,13,334.966667,0.000000,0.007692,0.0,0.0,Feb,1,1,1,4,Returning_Visitor,True,False
18,0,0.0,0,0.0,2,32.000000,0.000000,0.100000,0.0,0.0,Feb,2,2,1,3,Returning_Visitor,False,False
19,0,0.0,0,0.0,20,2981.166667,0.000000,0.010000,0.0,0.0,Feb,2,4,4,4,Returning_Visitor,False,False

Looks good, let's see how many rows and columns we have

In [9]:
data.shape

(12330, 18)

In [13]:
print(f'There are {data.shape[0]} rows and {data.shape[1]} columns')

There are 12330 rows and 18 columns

Looks like we have a given output variable which we can use as our taret, it is the 1st column, "Class". This seems like a intuitive, and most importantly useful, target to predict for, whether ther. If we were working for a bank this would be a great variable to predict!

In [14]:
feats = data.drop('Revenue', axis=1)
target = data['Revenue']
print(f'Features table has {feats.shape[0]} rows and {feats.shape[1]} columns')
print(f'Target table has {target.shape[0]} rows')

Features table has 12330 rows and 17 columns
Target table has 12330 rows

Looks good, let's save these as csvs for later.

In [16]:
target.head()

0    False
1    False
2    False
3    False
4    False
Name: Revenue, dtype: bool

Save the data out to csv files

In [15]:
feats.to_csv('../data/MY_OSI_feats.csv', index=False)
target.to_csv('../data/MY_OSI_target.csv', header='Revenue', index=False)